<#
.SYNOPSIS
    Checks every library in a CycloneDX SBOM against the OSV.dev vulnerability database.

.DESCRIPTION
    1. Reads target/bom.json (generated by the cyclonedx-maven-plugin during "mvnw package").
    2. Sends all package URLs to OSV's batch endpoint in one request.
    3. Fetches details (severity, CVE aliases, fixed versions) for each vulnerability found.
    4. Prints a summary and optionally writes a Markdown report.

    Works in Windows PowerShell 5.1 and PowerShell 7 (pwsh), so it also runs in CI.

.EXAMPLE
    .\mvnw.cmd -DskipTests package
    .\scripts\osv-scan.ps1 -Label "boot-2.7" -OutFile docs/security/scan-boot-2.7.md

.EXAMPLE
    # Fail the build if anything HIGH or CRITICAL is found (used in CI)
    pwsh scripts/osv-scan.ps1 -FailOn High
#>
param(
    [string]$Sbom = "target/bom.json",
    [string]$Label = "scan",
    [string]$OutFile = "",
    [ValidateSet("None", "Critical", "High", "Moderate")]
    [string]$FailOn = "None"
)

$ErrorActionPreference = "Stop"
$rank = @{ "CRITICAL" = 4; "HIGH" = 3; "MODERATE" = 2; "MEDIUM" = 2; "LOW" = 1; "UNKNOWN" = 0 }

if (-not (Test-Path $Sbom)) {
    throw "SBOM not found at '$Sbom'. Run '.\mvnw.cmd -DskipTests package' first."
}

# --- 1. Read the SBOM ------------------------------------------------------
$bom = Get-Content $Sbom -Raw | ConvertFrom-Json
$components = @($bom.components | Where-Object { $_.purl -like "pkg:maven/*" } | ForEach-Object {
    [pscustomobject]@{
        Name    = "$($_.group):$($_.name)"
        Version = $_.version
        # Drop qualifiers like "?type=jar"; OSV matches on name + version.
        Purl    = ($_.purl -split "\?")[0]
    }
})
Write-Host "Scanning $($components.Count) Maven components from $Sbom ..."

# --- 2. One batch query for everything --------------------------------------
$queries = @($components | ForEach-Object { @{ package = @{ purl = $_.Purl } } })
$body = @{ queries = $queries } | ConvertTo-Json -Depth 5
$batch = Invoke-RestMethod -Method Post -Uri "https://api.osv.dev/v1/querybatch" `
    -Body $body -ContentType "application/json"

# --- 3. Fetch details for each vulnerability (cached by id) -----------------
$details = @{}
function Get-VulnDetails([string]$id) {
    if (-not $details.ContainsKey($id)) {
        $details[$id] = Invoke-RestMethod -Uri "https://api.osv.dev/v1/vulns/$id"
    }
    return $details[$id]
}

function Get-Severity($vuln) {
    $sev = $null
    if ($vuln.database_specific -and $vuln.database_specific.severity) {
        $sev = "$($vuln.database_specific.severity)".ToUpperInvariant()
    }
    if (-not $sev -or -not $rank.ContainsKey($sev)) { $sev = "UNKNOWN" }
    return $sev
}

function Get-FixedVersions($vuln, [string]$packageName) {
    $fixed = @()
    foreach ($affected in @($vuln.affected)) {
        if ($affected.package.ecosystem -ne "Maven" -or $affected.package.name -ne $packageName) { continue }
        foreach ($range in @($affected.ranges)) {
            foreach ($event in @($range.events)) {
                if ($event.fixed) { $fixed += $event.fixed }
            }
        }
    }
    if ($fixed.Count -eq 0) { return "none published" }
    return (($fixed | Select-Object -Unique) -join ", ")
}

$findings = @()
for ($i = 0; $i -lt $components.Count; $i++) {
    $result = $batch.results[$i]
    if (-not $result -or -not $result.vulns) { continue }
    foreach ($v in @($result.vulns)) {
        $vuln = Get-VulnDetails $v.id
        $cves = @($vuln.aliases | Where-Object { $_ -like "CVE-*" })
        $summary = "$($vuln.summary)"
        if (-not $summary) { $summary = "(no summary)" }
        $findings += [pscustomobject]@{
            Severity = Get-Severity $vuln
            Package  = $components[$i].Name
            Version  = $components[$i].Version
            Id       = $v.id
            Cve      = ($cves -join ", ")
            Fixed    = Get-FixedVersions $vuln $components[$i].Name
            Summary  = $summary.Replace("|", "/")
        }
    }
}

$findings = @($findings | Sort-Object @{ Expression = { $rank[$_.Severity] }; Descending = $true }, Package)
$vulnerablePackages = @($findings | Select-Object -ExpandProperty Package -Unique)

# --- 4. Summary --------------------------------------------------------------
$counts = [ordered]@{}
foreach ($s in "CRITICAL", "HIGH", "MODERATE", "LOW", "UNKNOWN") {
    $counts[$s] = @($findings | Where-Object { $_.Severity -eq $s }).Count
}
Write-Host ""
Write-Host "=== OSV scan: $Label ==="
Write-Host ("{0} vulnerabilities in {1} of {2} packages" -f $findings.Count, $vulnerablePackages.Count, $components.Count)
$counts.GetEnumerator() | ForEach-Object { Write-Host ("  {0,-9} {1}" -f $_.Key, $_.Value) }

if ($OutFile) {
    $dir = Split-Path $OutFile -Parent
    if ($dir -and -not (Test-Path $dir)) { New-Item -ItemType Directory -Force -Path $dir | Out-Null }
    $lines = @()
    $lines += "# Dependency vulnerability scan: $Label"
    $lines += ""
    $lines += "- Scanned: $((Get-Date).ToString('yyyy-MM-dd')) against [OSV.dev](https://osv.dev)"
    $lines += "- Components (runtime scope): $($components.Count)"
    $lines += "- Vulnerabilities: **$($findings.Count)** across **$($vulnerablePackages.Count)** packages"
    $lines += ""
    $lines += "| Severity | Count |"
    $lines += "|---|---|"
    $counts.GetEnumerator() | ForEach-Object { $lines += "| $($_.Key) | $($_.Value) |" }
    $lines += ""
    if ($findings.Count -gt 0) {
        $lines += "| Severity | Package | Version | Advisory | CVE | Fixed in | Summary |"
        $lines += "|---|---|---|---|---|---|---|"
        foreach ($f in $findings) {
            $lines += "| $($f.Severity) | ``$($f.Package)`` | $($f.Version) | [$($f.Id)](https://osv.dev/vulnerability/$($f.Id)) | $($f.Cve) | $($f.Fixed) | $($f.Summary) |"
        }
    }
    Set-Content -Path $OutFile -Value $lines -Encoding UTF8
    Write-Host "Report written to $OutFile"
}

# --- 5. Optional quality gate -------------------------------------------------
if ($FailOn -ne "None") {
    $threshold = $rank[$FailOn.ToUpperInvariant()]
    $blocking = @($findings | Where-Object { $rank[$_.Severity] -ge $threshold })
    if ($blocking.Count -gt 0) {
        Write-Host "FAIL: $($blocking.Count) finding(s) at or above $FailOn." -ForegroundColor Red
        exit 1
    }
    Write-Host "PASS: nothing at or above $FailOn." -ForegroundColor Green
}
